apiVersion: v1
kind: Namespace
metadata:
  name: cosign-gatekeeper-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosign-gatekeeper-provider
  namespace: cosign-gatekeeper-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cosign-gatekeeper-provider
  template:
    metadata:
      labels:
        run: cosign-gatekeeper-provider
    spec:
      containers:
      - image: zosocanuck/cosign-gatekeeper-provider:certs
        imagePullPolicy: Never
        name: cosign-gatekeeper-provider
        ports:
        - containerPort: 8090
          protocol: TCP
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
